server:
  port: ${PORT:8085}
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: account-service
        uri: lb://rollingstone-ecommerce-account-api
        predicates:
        - Method=GET
        - Path=/api/account/**
        filters:
        - RewritePath=/api/account/(?<path>.*), /$\{path}